### ISSUE TITLE
Html content

### ISSUE THREAD

**Issue by alexey13** [WebReflection/uland#1]
Good day, Andrea!
It's not working for uland ${{html: htmlContent}} ?
[https://codepen.io/alexzhav/pen/RwrZPPw](https://codepen.io/alexzhav/pen/RwrZPPw)

**Comment by WebReflection** [comment]
no, but this works everywhere:

```js
render(document.body, html([htmlContent]));
```

**Comment by WebReflection** [comment]
if you have repeated use cases, use a `Map` to avoid re-parsing each time the same html _blob_.

```js
const fakeplates = new Map;
const setplate = html => {
  const fakeplate = [html];
  fakeplates.set(html, fakeplate);
  return fakeplate;
};

render(document.body, html(
  fakeplates.get(htmlContent) || setplate(htmlContent)
));
```

**Comment by WebReflection** [comment]
if you have static strings with interpolated values and you want to use these as arguments for template literals tag functions, [check tag-params](https://github.com/WebReflection/tag-params#readme) out.

**Comment by alexey13** [comment]
Get it, thanks a lot!
