### ISSUE TITLE
Components don't render in html.for

### ISSUE THREAD

**Issue by shiftyp** [WebReflection/uland#10]
## Description:

When using `html.for(...)` to render keyed elements, passing a uland `Component`, either directly or through a nested `html` template, does not render.

## Expected Behavior

The `Component` should render within keyed elements

## Reproduction

Here is a modified [codepen](https://codepen.io/shiftyp/pen/zYozpGQ) from the uhtml `html.for(...)` example. The key bit is reproduced below, along with the output:
### Code
```javascript
const Name = Component((name) => html`<span>${name}</span>`)
const update = (items) => {
  const ref = document.querySelector('.list-items');
  render(ref, html`
    <ul>
      ${items.map(
        ({id, name}) =>
          html.for(ref, id)`<li data-id=${id}>${Name(name)}</li>`
      )}
    </ul>`
  );
};
```
### Output
<img width="413" alt="Screen Shot 2021-02-18 at 1 03 57 PM" src="https://user-images.githubusercontent.com/131928/108400966-d2082580-71e9-11eb-92b7-29bd6aab000c.png">

**Comment by WebReflection** [comment]
Thanks for providing a minimal use-case example, it really helps!

I can confirm the behavior is not expected, so please bear with me, I'll fix this ASAP 👍

**Comment by WebReflection** [comment]
@shiftyp thee was a silly mistake within the code, and it got fixed. Everything should be fine now 👋
